classDiagram
    class Set {
        <<interface>>
        +add(E) boolean
        +remove(Object) boolean
        +contains(Object) boolean
    }
    class AbstractSet {
        <<abstract>>
    }
    class HashSet~E~ {
        -HashMap~E, Object~ map
        +add(E) boolean
        +contains(Object) boolean
        +remove(Object) boolean
    }
    class LinkedHashSet~E~ {
    }
    class HashMap~K,V~ {
        +put(K,V) V
        +get(Object) V
    }
    
    Set <|.. AbstractSet
    AbstractSet <|-- HashSet
    HashSet <|-- LinkedHashSet
    HashSet ..> HashMap : backed by
    Cloneable <|.. HashSet
    Serializable <|.. HashSet